---
title: "Economic Data - Lecture 7"
subtitle: "Sebastian Ellingsen"
author: "School of Economics - University of Bristol"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
      navigation:
        scroll: true # false if wish to disable scrolling by mouth and use keyboard only

---

```{r xaringan-themer, include=FALSE, warning=FALSE}
options(htmltools.dir.version = FALSE)

library(xaringanthemer)
style_mono_accent(
  base_color = "#1c5253")

options(htmltools.dir.version = FALSE)

# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, small.mar=TRUE, fig.retina = 5,message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
library(readxl)
library(scales)
library(ggthemes)
```


```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```







## After this lecture you should be able to

1. Explain the difference between register and survey (or ILO) unemployment.

2. Explain how the unemployment rate is calculated.

3. Explain and interpret the Phillips curve.

4. Explain and interpret the Beveridge curve.

5. Explain the intuition behind seasonal adjustment. 
---



## Data about the labour market

1) From the population to the labour force

2) The supply side (people supplying work)

3) The demand side (employers looking for workers)

4) The labour market and prices: The Phillips Curve

5) Demand meets Supply: The Beveridge Curve






---
class: inverse, center, middle

# Data About the Labor Market




---

## From population to labour force

The overall population of the UK ($\approx$ 66 mio in the UK)

- Children and elderly ($\approx$ 24 mio in the UK).

- Out of the labour force ($\approx$ 9 mio in the UK).

- The labour force ($\approx$ 33 mio in the UK) (also called the economic active).




---
## Out of the labour force

Also known as: The economic inactive

- Studying (≈ 27% in the UK)

- Looking after the family/staying home (≈ 24% in the UK) 

- Long-term sick (≈ 23% in the UK)

- Retired (≈ 13% in the UK)






---
## The labour force

The labour force = Unemployed + Employed

Unemployed (ILO definition) (The ILO is the International Labour Organisation)

- without a job, have been actively seeking work in the past four weeks and are available to start work in the next two weeks.

- out of work, have found a job and are waiting to start it in the next two weeks.

Employed (ILO definition)

- work at least one hour for pay in a week.

- temporarily away from jobs.

- on Government-supported training/employment programs.

- unpaid family work.


---

class: inverse, center, middle

$$\Large \text{Unemployment rate} = \frac{\text{Unemployed}}{\text{Unemployed} + \text{Employed}}$$


---






---

class: inverse, center, middle

# See you in the labs! 

Questions? $\texttt{sebastian.ellingsen@bristol.ac.uk}$.







