---
title: "Economic Data - Lecture 8"
subtitle: "Sebastian Ellingsen"
author: "School of Economics - University of Bristol"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
      navigation:
        scroll: true # false if wish to disable scrolling by mouth and use keyboard only

---

```{r xaringan-themer, include=FALSE, warning=FALSE}
options(htmltools.dir.version = FALSE)

library(xaringanthemer)
style_mono_accent(
  base_color = "#1c5253")

options(htmltools.dir.version = FALSE)

# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, fig.align="center",small.mar=TRUE, fig.retina = 5,message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
library(readxl)
library(scales)
library(ggthemes)
```


```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

<style>

.center2 {
  margin: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
}

</style>



## After this lecture you should be able to

Explain the 3 different types of interest rates.

Explain why interest vary 

Describe exchange rates










---
class: inverse, center, middle

# Interest Rates 





---

## What is an interest rate?

Assume you borrow some amount from a bank. 

The interest rate is then 

$$ i = \frac{\text{amount to repay}}{\text{amount borrowed}} - 1$$

Why do you have to pay interest to borrow? 

- Banks borrow and lend money on the money market. 

- Money in the future might be worth less due to inflation. 

- The bank could have invested the amount in stocks or bonds.

- Risk of the loan not being repaid.


---

## Annual or monthly interest rates

Data on interest rates are reported at different term periods.

Assume you borrow amount $B$ at time time and pay back $B^{\prime}$ in one year.

The annual interest: 

$$i = \frac{B^{\prime}}{B} - 1$$

The monthly interest: 

$$i = \frac{B^{\prime}}{B} - 1$$

The daily interest: 

$$i = \frac{B^{\prime}}{B} - 1$$








---

## Three important interest rates 

**Policy Rate**

- Set by the central bank

- Often based on an inflation target

- UK: "Bank of England Base Rate"



**Interbank Interest Rate**

- Banks charge each other

- UK: "Sterling OverNight Indexed Average" or "SONIA"


**Commercial lending rate**

- depends on repayment schedule, security/information, flexibility.





---

## plots here 





---

## The real interest rate

Data on interest rates are typically stated in nominal terms

- If I lend you money for a 2% annual interest rate and the inflation is 3% I lose.

- I can buy more for the 100£ I give you today, than for the 102£ you give me in one year.


The link between the real ($r$) and nominal interest $i$ rates are is the following: 

$$(1+i) = (1+r)(1+\pi) = 1 + r + \pi + \pi r$$

The *Fisher equation*: $r = i - \pi$

- The indentity is based on the assumption that $\pi r\approx 0$.







---

## Summary






---

class: inverse, center, middle

# See you in the labs! 

Questions? $\texttt{sebastian.ellingsen@bristol.ac.uk}$.







